version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: bullettrain
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
    api:
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        command: bin/docker-dev
        volumes:
            - .:/app
        environment:
            DJANGO_DB_NAME: bullettrain
            DJANGO_DB_USER: postgres
            DJANGO_DB_PASSWORD: password
            DJANGO_DB_PORT: 5432
            DJANGO_ALLOWED_HOSTS: localhost
            DJANGO_DB_HOST: db
            DATABASE_URL: postgres://postgres:password@db:5432/bullettrain
        ports:
            - '8000:8000'
        depends_on:
            - db
        links:
            - db:db
